version: "3"

services:
  onlyoffice:
      image: "onlyoffice/documentserver"
      container_name: inethi-onlyoffice
      hostname: inethi-onlyoffice
      tty: true
      restart: always
      ports:
        - "${ONLYOFFICE_PORT1}:80"
      networks:
        default:
          ipv4_address: "${ONLYOFFICE_IPV4}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"


