version: "3"

services:
  onlyoffice:
      image: "onlyoffice/communityserver"
      container_name: inethi-onlyoffice
      hostname: inethi-onlyoffice
      restart: always
      ports:
        - "${ONLYOFFICE_PORT1}:80"
        - "${ONLYOFFICE_PORT2}:443"
      volumes:
        - "${ONLYOFFICE_VOLUME}/lib:/var/lib"
        - "${ONLYOFFICE_VOLUME}/log:/var/log"
      networks:
        default:
          ipv4_address: "${ONLYOFFICE_IPV4}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"


