version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: inethi-mysql
    domainname: mysql.inethi.net
    hostname: mysql
    restart: always
    environment:
      MYSQL_USER: inethi
      - "MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${MYSQLDB_VOLUME}:/var/lib/mysql"
    networks:
      default:
        ipv4_address: "${MYSQLDB_IPV4}" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: inethi-phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
      - mysql
    restart: always
    hostname: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      "PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}"
    networks:
      default:
        ipv4_address: "${PHPMYADMIN_IPV4}"

networks:
  default:
    external:
      name: "${MYSQLDB_NETWORK}"
