version: '2'
services:
  encoder:
    image: ronaldod/avideo-encoder
    container_name: inethi-encoder
    environment:
      SITE_TITLE: "${ENCODER_SITE_TITLE}" 
      DOMAIN: "${ENCODER_DOMAIN}" 
      DOMAIN_PROTOCOL: "${ENCODER_DOMAIN_PROTOCOL}"
      ADMIN_PASSWORD: "${ENCODER_ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${ENCODER_ADMIN_EMAIL}"
      DB_HOST: "${ENCODER_DB_HOST}"
      DB_USER: "${ENCODER_DB_USER}"
      DB_PASSWORD: "${ENCODER_DB_PASSWORD}"
      LANG: "${ENCODER_LANG}"
    ports:
      - "${ENCODER_PORT}:80"
      - "${ENCODER_PORT_SECURE}:443"
    external_links:
      - inethi-mysql
    restart: always
    networks:
      default:
        ipv4_address: "${ENCODER_IPV4}"
  
  youphptube:
    image: ronaldod/avideo
    container_name: inethi-avideo
    environment:
      SITE_TITLE: "${AVIDEO_SITE_TITLE}" 
      DOMAIN: "${AVIDEO_DOMAIN}" 
      DOMAIN_PROTOCOL: "${AVIDEO_DOMAIN_PROTOCOL}"
      ADMIN_PASSWORD: "${AVIDEO_ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${AVIDEO_ADMIN_EMAIL}"
      DB_HOST: "${AVIDEO_DB_HOST}"
      DB_USER: "${AVIDEO_DB_USER}"
      DB_PASSWORD: "${AVIDEO_DB_PASSWORD}"
      LANG: "${AVIDEO_LANG}"
      Encoder_Port: "${ENCODER_PORT}"
    ports:
      - "${AVIDEO_PORT}:80"
      - "${AVIDEO_PORT_SECURE}:443"
    external_links:
      - inethi-mysql
    restart: always
    networks:
      default:
        ipv4_address: "${AVIDEO_IPV4}"

networks:
  default:
    external:
      name: inethi-bridge
